name: Unit testing for push and PR to the develop branch

on:
  push:
  workflow_dispatch:

jobs:
  pathtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install pytest
          python -m pip install .
      - name: Print config path
        run: |
          pwd
          find /opt -name testpkg.conf
          find /etc -name testpkg.conf
          find /usr -name testpkg.conf
          find /home -name testpkg.conf
